package etchosts

import (
	"bytes"
	"testing"
)

func TestExtractAndReplaceManagedBlock(t *testing.T) {
	initial := []byte(`127.0.0.1 localhost
::1 localhost
`)

	newBlock := []byte(`# BEGIN HOSTCLI
# Generated by hostcli.
192.168.1.10 api.local
# END HOSTCLI
`)

	// 1. Replace when no block exists (should append)
	merged, err := ReplaceManagedBlock(initial, newBlock)
	if err != nil {
		t.Fatalf("ReplaceManagedBlock failed: %v", err)
	}

	preamble, managed, suffix, err := ExtractManagedBlock(merged)
	if err != nil {
		t.Fatalf("ExtractManagedBlock failed: %v", err)
	}

	if !bytes.Contains(preamble, []byte("127.0.0.1 localhost")) {
		t.Errorf("preamble missing original content")
	}
	if !bytes.Equal(managed, newBlock) {
		t.Errorf("managed block mismatch. got:\n%s\nexpected:\n%s", string(managed), string(newBlock))
	}
	if len(suffix) != 0 {
		t.Errorf("expected empty suffix, got %q", string(suffix))
	}

	// 2. Replace existing block with an updated block
	updatedBlock := []byte(`# BEGIN HOSTCLI
# Generated by hostcli.
192.168.1.20 api.local
# END HOSTCLI
`)
	replaced, err := ReplaceManagedBlock(merged, updatedBlock)
	if err != nil {
		t.Fatalf("ReplaceManagedBlock on existing block failed: %v", err)
	}

	_, newManaged, _, _ := ExtractManagedBlock(replaced)
	if !bytes.Equal(newManaged, updatedBlock) {
		t.Errorf("expected updated managed block, got %s", string(newManaged))
	}

	// 3. Strip managed block (Rollback)
	stripped, err := StripManagedBlock(replaced)
	if err != nil {
		t.Fatalf("StripManagedBlock failed: %v", err)
	}

	if bytes.Contains(stripped, []byte("BEGIN HOSTCLI")) {
		t.Errorf("stripped content still contains BEGIN HOSTCLI")
	}
	if !bytes.Contains(stripped, []byte("127.0.0.1 localhost")) {
		t.Errorf("stripped content lost preamble")
	}
}
