package render

import (
	"fmt"
	"strings"

	"github.com/orekasep/go-hosts-cli/internal/core/etchosts"
	"github.com/orekasep/go-hosts-cli/internal/domain"
)

// RenderManagedBlock produces the complete managed block string,
// bounded by BeginMarker and EndMarker, including only enabled entries.
func RenderManagedBlock(hf *domain.HostsFile) string {
	var sb strings.Builder

	sb.WriteString(etchosts.BeginMarker)
	sb.WriteString("\n")
	sb.WriteString("# Generated by hostcli. Do not edit this block manually.\n")

	hasEntries := false
	for _, group := range hf.Groups {
		groupEntries := make([]domain.HostEntry, 0)
		for _, e := range group.Entries {
			if e.Enabled {
				groupEntries = append(groupEntries, e)
			}
		}

		if len(groupEntries) == 0 {
			continue
		}

		hasEntries = true
		sb.WriteString(fmt.Sprintf("\n# [%s]\n", group.Name))
		for _, e := range groupEntries {
			line := formatEntryLine(e)
			sb.WriteString(line)
			sb.WriteString("\n")
		}
	}

	if !hasEntries {
		sb.WriteString("# (No enabled host entries)\n")
	}

	sb.WriteString(etchosts.EndMarker)
	sb.WriteString("\n")

	return sb.String()
}

func formatEntryLine(e domain.HostEntry) string {
	var parts []string
	parts = append(parts, e.IP)
	parts = append(parts, e.Hostname)
	for _, alias := range e.Aliases {
		if strings.TrimSpace(alias) != "" {
			parts = append(parts, strings.TrimSpace(alias))
		}
	}

	line := strings.Join(parts, "\t")
	if e.Comment != "" {
		line += fmt.Sprintf("\t# %s", e.Comment)
	}
	return line
}
